export enum ECartActions {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_ITEM = "REMOVE_ITEM",
  SUB_QUANTITY = "SUB_QUANTITY",
  ADD_QUANTITY = "ADD_QUANTITY"
}

export enum EProductActions {
  FETCH_PRODUCTS = "FETCH_PRODUCTS",
  FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN",
  FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE"
}
